/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * changedata.java
 *
 * Created on Jul 2, 2012, 12:57:54 AM
 */
package cyber.medallians;

import DBManage.DBManager;
import DBManage.DatabaseConnector;
import UniqueClasses.ConsumerController;
import UniqueClasses.ConsumerModel;
import UniqueClasses.Metermodel;
import UniqueClasses.hastopayController;
import UniqueClasses.metercontroller;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import resources.ApplyTheme;

/**
 *
 * @author DELL
 */
public class removeandchange extends javax.swing.JFrame {
    String meterID;
   static String name1;
    

    DefaultTableModel defaultTableModel;

    /** Creates new form changedata */
    public removeandchange() {
        initComponents();
        setLocationRelativeTo(null);
        defaultTableModel = (DefaultTableModel) jtblCMH.getModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbsearchitem = new javax.swing.JComboBox();
        jtfHasToSearch = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfname = new javax.swing.JTextField();
        jtftelephoneno = new javax.swing.JTextField();
        jtfnic = new javax.swing.JTextField();
        jtfmaincity = new javax.swing.JTextField();
        jtfhometown = new javax.swing.JTextField();
        jtfstreet = new javax.swing.JTextField();
        jtfhomeno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCMH = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfconnecteddate = new javax.swing.JTextField();
        jtfmadein = new javax.swing.JTextField();
        jtfrpu = new javax.swing.JTextField();
        jtfmeternno = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfaccountid = new javax.swing.JTextField();
        jtftotalamount = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbtRemove = new javax.swing.JButton();
        jbtChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove And Change [Ceylon Electricity Board]");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Remove and Change");
        jLabel1.setBounds(390, 20, 230, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Select search type ");

        jcbsearchitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By name", "ByID", "By NIC" }));

        jtfHasToSearch.setBackground(new java.awt.Color(153, 255, 255));
        jtfHasToSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHasToSearchActionPerformed(evt);
            }
        });

        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfHasToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jcbsearchitem, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbsearchitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfHasToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearch))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBounds(0, 60, 400, 90);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Concumer"));

        jLabel3.setText("Name");

        jLabel4.setText("Telephone No");

        jLabel5.setText("NIC");

        jLabel6.setText("Main City");

        jLabel7.setText("Home town");

        jLabel8.setText("Street");

        jLabel9.setText("Home Name/No");

        jtfnic.setEditable(false);

        jtfmaincity.setEditable(false);

        jtfhometown.setEditable(false);

        jtfstreet.setEditable(false);
        jtfstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfstreetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfhomeno)
                    .addComponent(jtfhometown)
                    .addComponent(jtfmaincity)
                    .addComponent(jtfnic)
                    .addComponent(jtftelephoneno)
                    .addComponent(jtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jtfstreet, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtftelephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jtfmaincity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfhometown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfhomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        jPanel3.setBounds(10, 160, 390, 280);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtblCMH.setBackground(new java.awt.Color(153, 255, 255));
        jtblCMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Meter No", "Connected date", "has to pay", "Account No"
            }
        ));
        jtblCMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblCMHMouseClicked(evt);
            }
        });
        jtblCMH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jtblCMHMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(jtblCMH);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBounds(410, 60, 610, 220);
        jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Meter"));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Meter No");

        jLabel11.setText("RPU");

        jLabel12.setText("Made IN");

        jLabel13.setText("Connected date");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfmeternno, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jtfmadein, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jtfrpu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jtfconnecteddate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfmeternno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfrpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmadein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfconnecteddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBounds(408, 290, 300, 150);
        jLayeredPane1.add(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Clear All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel9.setBounds(580, 450, 360, 50);
        jLayeredPane1.add(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill datails"));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Account No");

        jLabel17.setText("Has to pay");

        jtfaccountid.setEditable(false);

        jtftotalamount.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtftotalamount)
                            .addComponent(jtfaccountid, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(400, 400, 400))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfaccountid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtftotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBounds(730, 290, 250, 150);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtRemove.setText("Remove");
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });

        jbtChange.setText("Change");
        jbtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jbtChange)
                .addGap(18, 18, 18)
                .addComponent(jbtRemove)
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBounds(310, 450, 210, 60);
        jLayeredPane1.add(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtfstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfstreetActionPerformed
}//GEN-LAST:event_jtfstreetActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    MainWindow MainWindow = new MainWindow();
   // MainWindow.setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    System.exit(0);
}//GEN-LAST:event_jButton5ActionPerformed

private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed

    String hasToSearch = jtfHasToSearch.getText();
    int selection = jcbsearchitem.getSelectedIndex();
    String searchToDelete = null;
    if(selection == 0){
    searchToDelete = "select name,tlpno,nic,maincity,hometown,street,homeno,amount,meter_no,amount,account_no,connected_date from consumer c,hastopay h,meter m where c.owner_id=m.owner_id and c.owner_id=h.owner_id and c.name='" + hasToSearch + "'";  
    }
    else if(selection == 1){
    searchToDelete = "select name,tlpno,nic,maincity,hometown,street,homeno,amount,meter_no,amount,account_no,connected_date from consumer c,hastopay h,meter m where c.owner_id=m.owner_id and c.owner_id=h.owner_id and c.owner_id='" + hasToSearch + "'";
    }
    else{
   searchToDelete = "select name,tlpno,nic,maincity,hometown,street,homeno,amount,meter_no,amount,account_no,connected_date from consumer c,hastopay h,meter m where c.owner_id=m.owner_id and c.owner_id=h.owner_id and c.nic='" + hasToSearch + "'";
    }
    int rowcount = jtblCMH.getRowCount();//get row count in the tablr
    for (int i = 0; i < rowcount; i++) {
        defaultTableModel.removeRow(0);
    }
jtfname.setText("");
jtfhomeno.setText("");
jtfhometown.setText("");
jtfmadein.setText("");
jtfmaincity.setText("");
jtfmeternno.setText("");
jtfnic.setText("");
jtfrpu.setText("");
jtfstreet.setText("");
jtftelephoneno.setText("");
jtftotalamount.setText("");

    try {
        Connection connection = DatabaseConnector.makeConnection();
        ResultSet resultSet = DBManager.getData(connection, searchToDelete);
        while (resultSet.next()) {
            Object dataRow[] = {resultSet.getString("meter_no"), resultSet.getString("connected_date"), resultSet.getString("amount"), resultSet.getString("account_no")};
            defaultTableModel.addRow(dataRow);
            
            jtfname.setText(resultSet.getString("name"));
            jtftelephoneno.setText(resultSet.getString("tlpno"));
            jtfnic.setText(resultSet.getString("nic"));
            jtfmaincity.setText(resultSet.getString("maincity"));
            jtfhometown.setText(resultSet.getString("hometown"));
            jtfstreet.setText(resultSet.getString("street"));
            jtfhomeno.setText(resultSet.getString("homeno"));
            
            name1=resultSet.getString("name");
      }
        System.out.println(name1);
       if(name1 == null) {
            JOptionPane.showMessageDialog(rootPane,"No Connection Data Result \n        Customer  : "+ hasToSearch);
       }
          

    } catch (SQLException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }

 /*   String Regno = jtfHasToSearch.getText();
    ResultSet resultSet = null;
    ConsumerModel cmd = new ConsumerModel();
    cmd.setOwnerID(Regno);
    try {
        resultSet = ConsumerController.cusSearchByRegno(cmd);
    } catch (SQLException ex) {
        Logger.getLogger(SearchConsumer.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(SearchConsumer.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        while (resultSet.next()) {
            jtfname.setText(resultSet.getString("name"));
            jtftelephoneno.setText(resultSet.getString("tlpno"));
            jtfnic.setText(resultSet.getString("nic"));
            jtfmaincity.setText(resultSet.getString("maincity"));
            jtfhometown.setText(resultSet.getString("hometown"));
            jtfstreet.setText(resultSet.getString("street"));
            jtfhomeno.setText(resultSet.getString("homeno"));

        }
    } catch (SQLException ex) {
        Logger.getLogger(SearchConsumer.class.getName()).log(Level.SEVERE, null, ex);
    }
*/
}//GEN-LAST:event_jbtSearchActionPerformed

private void jtblCMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblCMHMouseClicked

    int row = jtblCMH.getSelectedRow();
    System.out.println(row);
    String meterNo = (String) defaultTableModel.getValueAt(row, 0);
    String accountNo = (String) defaultTableModel.getValueAt(row, 3);

    System.out.println(meterNo);
    System.out.println(accountNo);



    ResultSet resultSet = null;
    ResultSet resultSetforAcc = null;
    Metermodel metermodel = new Metermodel();
    metermodel.setMeterNo(meterNo);
    try {
        resultSet = metercontroller.searchMeterByMeterNo(metermodel);
        while (resultSet.next()) {
            meterID=resultSet.getString("Meter_id");
            jtfmeternno.setText(resultSet.getString("Meter_no"));
            jtfrpu.setText(resultSet.getString("rpu"));
            jtfmadein.setText(resultSet.getString("made_in"));
            jtfconnecteddate.setText(resultSet.getString("connected_date"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }


    /*  try {
    Connection connection = DatabaseConnector.makeConnection();
    String sql="SELECT * FROM hastopay where account_id=121213133";
    resultSet = DBManager.getData(connection,accountNo);
    while(resultSet.next()){
    jtfaccountid.setText(resultSet.getString("rpu"));
    jtftotalamount.setText(resultSet.getString("rpu"));
    }
    } catch (SQLException ex) {
    Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex){
    Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }
     */
    double netAmount=0;
    jtfaccountid.setText(accountNo);
    try {
        resultSetforAcc = hastopayController.getAccountDetails(accountNo);
        while(resultSetforAcc.next()){
            netAmount+=Double.parseDouble(resultSetforAcc.getString("amount"));
        }
        System.out.println("netAmount :"+netAmount);
        jtftotalamount.setText(Double.toString(netAmount));
    } catch (SQLException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }

}//GEN-LAST:event_jtblCMHMouseClicked

private void jbtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChangeActionPerformed
    String ownerID = jtfHasToSearch.getText();
    String name = jtfname.getText();
    String telephoneNo = jtftelephoneno.getText();
    String nic = jtfnic.getText();
    String mainCity = jtfmaincity.getText();
    String homeTown = jtfhometown.getText();
    String street = jtfstreet.getText();
    String homeNo = jtfhomeno.getText();
    
    String meterNo=jtfmeternno.getText();
    String rpu=jtfrpu.getText();
    String madeIn=jtfmadein.getText();
    String connectedDate=jtfconnecteddate.getText();

    ConsumerModel consumerModel = new ConsumerModel(ownerID, name, nic, homeNo, street, homeTown, mainCity, telephoneNo);
    Metermodel metermodel=new Metermodel(meterID, meterNo, rpu, connectedDate, madeIn, ownerID);
    
    int result = 0;
    int resultOfMeter=0;
    try {
        result = ConsumerController.updateConsumer(consumerModel);
    } catch (SQLException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }
    if (result > 0) {
        JOptionPane.showMessageDialog(jtftelephoneno, "Update database in Succsesfully");
    } else {
        JOptionPane.showMessageDialog(jtftelephoneno, "Update database not sussecesfully ?");
    }
        try {
            resultOfMeter=metercontroller.updateMeter(metermodel);
            
        } catch (SQLException ex) {
            Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(resultOfMeter>0){
            System.out.println("Meter Successfully Updated");
        }

}//GEN-LAST:event_jbtChangeActionPerformed

private void jtfHasToSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHasToSearchActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jtfHasToSearchActionPerformed

private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
   String ownerID = jtfHasToSearch.getText();
    ConsumerModel consumerModel = new ConsumerModel();
    consumerModel.setOwnerID(ownerID);
    int result = 0;
    try {
        
        int rsaddtodisable =0;
        ResultSet rssearch1=null;
        Connection connection = DatabaseConnector.makeConnection();
        String SqlForresult1 ="select c.owner_id,c.name,m.meter_id,c.maincity,c.nic,c.street,c.homeno,c.tlpno,c.hometown,m.meter_no ,h.amount from consumer as c,meter as m ,hastopay as h where c.owner_id=m.owner_id and c.owner_id=h.owner_id and c.owner_id='"+ownerID+"'";
        rssearch1 = DBManager.getData(connection, SqlForresult1);
        
        while(rssearch1.next()){
        String sqlForAddDeleteDetails = "insert into disable(cust_id,Cust_name,nic,homecity,street,homeno,meterID,meterno,hastopay,telephone_no) values('" + rssearch1.getString("c.owner_id") + "','" + rssearch1.getString("c.name") + "','" + rssearch1.getString("c.nic") + "','" + rssearch1.getString("c.maincity") + "','" + rssearch1.getString("c.street") + "','" + rssearch1.getString("c.homeno") + "','" + rssearch1.getString("m.meter_id") + "','" + rssearch1.getString("m.meter_no") + "','" + rssearch1.getString("h.amount") + "','" + rssearch1.getString("c.tlpno") + "') ";
        rsaddtodisable = DBManager.SendData(connection,sqlForAddDeleteDetails);
        
        
        
        }
                
        
        
       // String sqlForAddDeleteDetails = "insert into disable(cust_ID,Cust_name,nic,homecity,street,homeno,disconneted_date,meterID,meter_no,hastopay,tetephone_no) values"
        
        
        result = ConsumerController.deleteConsumer(consumerModel);
        
        
   
    } catch (SQLException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(removeandchange.class.getName()).log(Level.SEVERE, null, ex);
    }
    if (result > 0) {
        JOptionPane.showMessageDialog(jtftelephoneno, "Added the Data to Disable List");
        JOptionPane.showMessageDialog(jtftelephoneno, "Delete Data in database in sussesfully");
    } else {
        JOptionPane.showMessageDialog(jtftelephoneno, "Can't Delete these data");
    }




}//GEN-LAST:event_jbtRemoveActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jtfname.setText("");
jtfaccountid.setText("");
jtfHasToSearch.setText("");
jtfconnecteddate.setText("");
jtfhomeno.setText("");
jtfhometown.setText("");
jtfmadein.setText("");
jtfmaincity.setText("");
jtfmeternno.setText("");
jtfnic.setText("");
jtfrpu.setText("");
jtfstreet.setText("");
jtfname.setText("");
jtftelephoneno.setText("");
jtftotalamount.setText("");

int rowcount = jtblCMH.getRowCount();
    for (int i = 0; i < rowcount; i++) {
        defaultTableModel.removeRow(0);
    }


}//GEN-LAST:event_jButton1ActionPerformed

private void jtblCMHMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblCMHMouseMoved
    
    
    
}//GEN-LAST:event_jtblCMHMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeandchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeandchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeandchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeandchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ApplyTheme.Theme();
                new removeandchange().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtChange;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JComboBox jcbsearchitem;
    private javax.swing.JTable jtblCMH;
    private javax.swing.JTextField jtfHasToSearch;
    private javax.swing.JTextField jtfaccountid;
    private javax.swing.JTextField jtfconnecteddate;
    private javax.swing.JTextField jtfhomeno;
    private javax.swing.JTextField jtfhometown;
    private javax.swing.JTextField jtfmadein;
    private javax.swing.JTextField jtfmaincity;
    private javax.swing.JTextField jtfmeternno;
    private javax.swing.JTextField jtfname;
    private javax.swing.JTextField jtfnic;
    private javax.swing.JTextField jtfrpu;
    private javax.swing.JTextField jtfstreet;
    private javax.swing.JTextField jtftelephoneno;
    private javax.swing.JTextField jtftotalamount;
    // End of variables declaration//GEN-END:variables
}
