/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SMStaker.java
 *
 * Created on Sep 24, 2012, 10:35:37 PM
 */
package cyber.medallians;

import DBManage.DBManager;
import DBManage.DatabaseConnector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import resources.ApplyTheme;

/**
 *
 * @author DELL
 */
public class SMStaker extends javax.swing.JFrame {

    String sendernumber;
    String smstext;
    String meterno;
    String meterid;
    String ownerid;
    String meterid2;
    String sentDate;
    String smsID;
    String readingIDNew;
    String smsDate;
    String smsTime;
    String readingValue;

    /** Creates new form SMStaker */
    public SMStaker() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS Taker [Ceylon Electricity Board]");

        jButton1.setText("SMS taker");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("SMS Taker");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images (5).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        ResultSet rsgetunitsfmsms = null;
        ResultSet rsMetreIdOfMeter = null;
        ResultSet rsCustIdOfMeter = null;
        ResultSet rsReadindIdgen = null;

        Connection connection = DatabaseConnector.makeConnection();
        String sqlForGetUnits = "select id,sms_text,sender_number,sent_dt from sms_in where sms_text like 'TOU%'";

        rsgetunitsfmsms = DBManager.getData(connection, sqlForGetUnits);

        while (rsgetunitsfmsms.next()) {
            System.out.println(rsgetunitsfmsms.getString("sms_text"));
            System.out.println(rsgetunitsfmsms.getString("sender_number"));
            System.out.println(rsgetunitsfmsms.getString("sent_dt"));
            smsID = rsgetunitsfmsms.getString("id");
            sendernumber = rsgetunitsfmsms.getString("sender_number");
            smstext = rsgetunitsfmsms.getString("sms_text");
            sentDate = rsgetunitsfmsms.getString("sent_dt");

            System.out.println("sendernumber" + sendernumber);
            System.out.println("smstext" + smstext);
            System.out.println("sebtDate" + sentDate);
            System.out.println("id" + smsID);

            ////////////////////////Reading Id Gen//////////////////////////////
            String sqlforReadinIdGen = "select reading_id from reading";
            Connection connection22 = DatabaseConnector.makeConnection();
            rsReadindIdgen = DBManager.getData(connection, sqlforReadinIdGen);
            int maxID = 0;
            while (rsReadindIdgen.next()) {
                String readingID = rsReadindIdgen.getString("reading_id");
                System.out.println("readingId" + readingID);
                readingID = readingID.replace("r", "0").replace("i", "0").replace("d", "0");
                int readingIdNo = Integer.parseInt(readingID);
                if (readingIdNo > maxID) {
                    maxID = readingIdNo;
                }
            }
            maxID += 1;
            readingIDNew = "rid" + maxID;
            System.out.println("newReading Id" + readingIDNew);

            ////////////////////////Reading Id Gen//////////////////////////////

            ////////////////////////Date And Time///////////////////////////////
            StringTokenizer tokenizer = new StringTokenizer(sentDate, " ");
            while (tokenizer.hasMoreTokens()) {
                smsDate = tokenizer.nextToken();
                smsTime = tokenizer.nextToken();
                System.out.println("Date" + smsDate);
                System.out.println("Time" + smsTime);
            }
            ////////////////////////Date And Time///////////////////////////////

            ///////////////////////Reading Value////////////////////////////////
            StringTokenizer tokenizer2 = new StringTokenizer(smstext, " ");
            while (tokenizer2.hasMoreTokens()) {
                tokenizer2.nextToken();
                readingValue = tokenizer2.nextToken();
                System.out.println("readingValue" + readingValue);
            }
            ///////////////////////Reading Value////////////////////////////////

            ///////////////////////MeterID//////////////////////////////////////
            String sqlformeterID = "select meter_no,meter_id from meter where sim_number_meter='" + sendernumber + "'";
            rsMetreIdOfMeter = DBManager.getData(connection, sqlformeterID);
            while (rsMetreIdOfMeter.next()) {

                System.out.println(rsMetreIdOfMeter.getString("meter_no"));
                System.out.println(rsMetreIdOfMeter.getString("meter_id"));
                meterno = rsMetreIdOfMeter.getString("meter_no");
                meterid = rsMetreIdOfMeter.getString("meter_id");
                System.out.println("meterNo" + meterno);
                System.out.println("meterid" + meterid);
            }

            System.out.println("******" + readingIDNew);
            System.out.println("******" + smsDate);
            System.out.println("******" + smsTime);
            System.out.println("******" + readingValue);
            System.out.println("******" + meterid);
            ///////////////////////MeterID//////////////////////////////////////

            ///////////////////////Make Reading/////////////////////////////////
            String sqlForReadingGent = "Insert into reading(reading_id, dates, times, units, meter_id, RDState) values('" + readingIDNew + "','" + smsDate + "','" + smsTime + "','" + readingValue + "','" + meterid + "','n')";
            Connection connection33 = DatabaseConnector.makeConnection();
            int result33 =0;
             result33 = DBManager.SendData(connection33, sqlForReadingGent);
            if(result33>0){
                JOptionPane.showMessageDialog(rootPane, "Added to the Reading", "RD State", 1);
            }
            ///////////////////////Make Reading/////////////////////////////////
            
            ///////////////////////Delete from SmsIN////////////////////////////
            String sqlForDelete="delete from sms_in where id='"+smsID+"'";
            Connection connection44 = DatabaseConnector.makeConnection();
            int result44 =0;
             result44 = DBManager.SendData(connection44, sqlForDelete);
            if(result44>0){
                JOptionPane.showMessageDialog(rootPane, "Deleted From smsIn", "SMS State", 1);
            }
            
            ///////////////////////Delete from SmsIN////////////////////////////

        }








    } catch (SQLException ex) {
        Logger.getLogger(SMStaker.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(SMStaker.class.getName()).log(Level.SEVERE, null, ex);
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    MainWindow MainWindow = new MainWindow();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMStaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMStaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMStaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMStaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                 ApplyTheme.Theme();
                new SMStaker().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
